language: go

os:
  - linux
  - osx
  - windows

go:
  - tip
  - 1.12
  - 1.11

env:
  - GO111MODULE=on

script:
  - go test -v -coverprofile=coverage.txt -covermode=atomic ./...

after_success: bash <(curl -s https://codecov.io/bash)

matrix:
  allow_failures:
    - go: tip
